name: Run Rust Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_rust_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install Rust using dtolnay/rust-toolchain
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable  # You can specify a specific version if needed

      # Build the Rust project
      - name: Build Rust project
        run: cargo build --verbose

      # Run the main binary if main.rs exists
      - name: Run main binary
        run: |
          if [ -f "src/main.rs" ]; then
            echo "Running main binary..."
            cargo run
          else
            echo "No main.rs found, skipping execution."
          fi

      # Run additional binaries inside src/bin/ but skip my_module.rs
      - name: Run additional binaries
        run: |
          if [ -d "src/bin" ]; then
            for file in src/bin/*.rs; do
              if [[ -f "$file" ]]; then
                filename=$(basename -- "$file")
                filename_no_ext="${filename%.*}"

                # Skip my_module.rs
                if [[ "$filename_no_ext" == "my_module" ]]; then
                  echo "Skipping module: $filename_no_ext"
                  continue
                fi

                echo "Running binary: $filename_no_ext..."
                cargo run --bin "$filename_no_ext"
              fi
            done
          else
            echo "No additional binaries found in src/bin."
          fi
