# name: Run Rust Files

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   run_rust_files:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       # Install Rust
#       - name: Set up Rust
#         uses: actions/setup-rust@v1
#         with:
#           rust-version: 1.56.0  # You can change to the desired version

#       # Check if file exists and run it
#       - name: Run file 1
#         if: ${{ exists('src/Hello_World.rs') }}
#         run: |
#           cargo run --bin Hello_World

#       - name: Run file 2
#         if: ${{ exists('src/Variable_Data_Types.rs') }}
#         run: |
#           cargo run --bin Variable_Data_Types

#       - name: Run file 3
#         if: ${{ exists('src/Conditionals.rs') }}
#         run: |
#           cargo run --bin Conditionals

#       - name: Run file 4
#         if: ${{ exists('src/Loops.rs') }}
#         run: |
#           cargo run --bin Loops

#       - name: Run file 5
#         if: ${{ exists('src/Functions.rs') }}
#         run: |
#           cargo run --bin Functions

#       - name: Run file 6
#         if: ${{ exists('src/Structs.rs') }}
#         run: |
#           cargo run --bin Structs

#       - name: Run file 7
#         if: ${{ exists('src/Enums.rs') }}
#         run: |
#           cargo run --bin Enums

#       - name: Run file 8
#         if: ${{ exists('src/Pattern_Matching.rs') }}
#         run: |
#           cargo run --bin Pattern_Matching

#       - name: Run file 9
#         if: ${{ exists('src/Ownership_Borrowing_References.rs') }}
#         run: |
#           cargo run --bin Ownership_Borrowing_References

#       - name: Run file 10
#         if: ${{ exists('src/Concurrency.rs') }}
#         run: |
#           cargo run --bin Concurrency

#       - name: Run file 11
#         if: ${{ exists('src/Error_Handling.rs') }}
#         run: |
#           cargo run --bin Error_Handling

#       - name: Run file 12
#         if: ${{ exists('src/Closures.rs') }}
#         run: |
#           cargo run --bin Closures

#       - name: Run file 13
#         if: ${{ exists('src/Traits.rs') }}
#         run: |
#           cargo run --bin Traits

#       - name: Run file 14
#         if: ${{ exists('src/Collections.rs') }}
#         run: |
#           cargo run --bin Collections

#       - name: Run file 15
#         if: ${{ exists('src/Working_with_Modules.rs') }}
#         run: |
#           cargo run --bin Working_with_Modules

name: Run Rust Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_rust_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install Rust using dtolnay/rust-toolchain
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable  # You can specify a specific version if needed

      # Run Rust files if they exist
      - name: Run Rust files
        run: |
          for file in src/*.rs; do
            if [[ -f "$file" ]]; then
              filename=$(basename -- "$file")
              filename_no_ext="${filename%.*}"
              echo "Running $filename_no_ext..."
              cargo run --bin "$filename_no_ext"
            fi
          done
